# Generated by Django 5.2.4 on 2025-07-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attacker_card", models.PositiveIntegerField()),
                ("defender_card", models.PositiveIntegerField(blank=True, null=True)),
                ("rule", models.BooleanField()),
                ("is_over", models.BooleanField(default=False)),
            ],
        ),
    ]
