# Generated by Django 5.2.4 on 2025-07-18 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.PositiveIntegerField()),
                ('defender_card', models.PositiveIntegerField(blank=True, null=True)),
                ('rule', models.BooleanField()),
                ('is_over', models.BooleanField(default=False)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_attacker', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_defender', to=settings.AUTH_USER_MODEL)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_loser', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
